function cornici(title)
global AQUAMARINE RELDATA
if title == 'yes'
   uicontrol('Units','normalized',...
      'Position',[0.2 0.9 0.5 0.1],...
      'Style','Text',...
      'String','FEM 1D - Rel.1.0','FontAngle','oblique',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','bold','FontSize',[18]);  % titolo
end
uicontrol('Units','normalized',...
   'Position',[0.5 0 0.5 0.05],'HorizontalAlignment','right',...
   'Style','Text',...
   'String','Authors: F.Saleri, A.Veneziani (Copyright 2000)',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[8]); 
uicontrol('Units','normalized',...
   'Position',[0 0 0.5 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String',RELDATA,'FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[8]);
return