function femdefhyp
%
%FEMDEFHYP 1-d finite element definitions.
%
%   See also FEM1D.

%   Reference: A. Quarteroni, Modellistica Numerica 
%   per Problemi Differenziali, Springer-Italia, Milano
%   (2000).

%   Fausto Saleri, Alessandro Veneziani
%   $Revision: 1.1.1.1 $  $Date: 2001/03/09 08:22:48 $
global AQUAMARINE RELDATA METODO SOLVER
global MODUS FEMSYS GERBASE HMESH QUADRA
global FATHER FORMA CHOICE
global DELTAT OMEGA LUMPING
%
%[m,n]=size(FATHER)
%if n>2
%   close(FATHER(3));
%end;   
% Posiziona la figura
[figurePos]=pos_figure;
%
% Crea la figura
advanced = get(MODUS,'Value');
if ( advanced == 0) 
   FATHER(3)=figure('NumberTitle','off','Color',AQUAMARINE,...
      'Units','points',...
      'MenuBar','none','Name',...
      'Fem 1D: Finite Element definition (simple mode)             ',...
      'Resize','off','Position',figurePos);
else
   FATHER(3)=figure('NumberTitle','off','Color',AQUAMARINE,...
      'Units','points',...
      'MenuBar','none','Name',...
      'Fem 1D: Finite Element definition (advanced mode)            ',...
      'Resize','off','Position',figurePos);
end
%
% Costruisce titolo, autori e release
cornici('no ');
uicontrol('Units','normalized',...
   'Position',[0 0.95 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','Input the attributes  ofthe numerical scheme :',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
%
% Tipo di elemento finito
uicontrol('Units','normalized',...
   'Position',[0.05 0.8 0.4 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','Finite Element Type    :',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
   'FontWeight','demi','FontSize',[10]); 
s='String';
FEMSYS=uicontrol('Units','normalized',...
   'Position',[0.35 0.81 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Popup','String',['P1';'P2';'P3'],...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'ForegroundColor','blue',...
   'CallBack','degre=get(FEMSYS,value);if degre>1, set(LUMPING,value,0);set(LUMPING,visible,OFF);else, set(LUMPING,visible,ON); end;'); 
degre=get(FEMSYS,'Value');
if (degre==1) 
LUMPING=uicontrol('Units','normalized',...
      'Position',[0.55 0.1 0.4 0.1],'HorizontalAlignment','left',...
      'Style','radiobutton','String','Mass Lumping (only P1)', 'Value',0,...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10],'CallBack','time_step=delta_t_set, set(DELTAT,stringa,num2str(time_step));');
else
LUMPING=uicontrol('Units','normalized',...
      'Position',[0.35 0.1 0.4 0.1],'HorizontalAlignment','left',...
      'Style','radiobutton','String','P1 ML', 'Value',0,...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10],'Visible','off','CallBack','time_step=delta_t_set;set(DELTAT,stringa,num2str(time_step));');
end;
if advanced ~= 0    % basi gerarchiche solo in modalita' avanzata
   uicontrol('Units','normalized',...
      'Position',[0.47 0.8 0.4 0.05],'HorizontalAlignment','left',...
      'Style','text','String','(hierarchical base      )',...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10]);
   GERBASE=uicontrol('Units','normalized',...
      'Position',[0.71 0.81 0.02 0.03],'HorizontalAlignment','left',...
      'Style','radiobutton','String',' ',...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10]);
else
   GERBASE=uicontrol('Units','normalized',...
      'Position',[0.69 0.81 0.02 0.03],'HorizontalAlignment','left',...
      'Style','radiobutton','String',' ','Value',0,...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10],'Visible','off');
end
% Tipo di griglia
if advanced == 0    % griglie non uniformi solo in modalita' avanzata  
   uicontrol('Units','normalized',...
      'Position',[0.05 0.7 0.4 0.05],'HorizontalAlignment','left',...
      'Style','Text',...
      'String','Grid Spacing (uniform):',...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10]); 
   HMESH =uicontrol('Units','normalized',...
      'Position',[0.41 0.7 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0.1',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],...
      'ForegroundColor','blue','CallBack','time_step=delta_t_set;set(DELTAT,stringa,num2str(time_step));'); 
   QUADRA =uicontrol('Position',...
      [figurePos(1)+305 figurePos(2)+175 30 20],...
      'Style','edit','String','7',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],...
      'ForegroundColor','blue','Visible','off');   
else
   uicontrol('Units','normalized',...
      'Position',[0.05 0.7 0.4 0.05],'HorizontalAlignment','left',...
      'Style','Text',...
      'String','Grid Spacing as function of x     :',...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10]);
   HMESH =uicontrol('Units','normalized',...
      'Position',[0.47 0.7 0.3 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0.1*(1+exp(-x))',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue',...
       'CallBack','time_step=delta_t_set;set(DELTAT,stringa,num2str(time_step));');
   uicontrol('Units','normalized',...
      'Position',[0.05 0.6 0.6 0.05],'HorizontalAlignment','left',...
      'Style','Text',...
      'String','N.ro dei nodi della formula di quadratura di GLL: ',...
      'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
      'FontWeight','demi','FontSize',[10]);
   QUADRA =uicontrol('Units','normalized',...
      'Position',[0.67 0.6 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','7',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue');
end
hmesh = get(HMESH,'String');

%
% Tipo di metodo (da scegliersi solo in modalita' avanzata)
if advanced == 0
   METODO=uicontrol('Units','normalized',...
      'Position',[0.05 0.5 0.6 0.05],'HorizontalAlignment','left',...
      'Style','popup','Value',2,...
      'String',['Forward Euler          ';...
         'Backward Euler         ';...
         'Upwind                 ';...
         'Lax-Wendroff           ';],...
      'BackgroundColor',AQUAMARINE,'Visible','off',...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue',...
      'CallBack','time_step=delta_t_set,set(DELTAT,stringa,num2str(time_step));');
   SOLVER(1)=uicontrol('Units','normalized',...
      'Position',[0.45 0.41 0.45 0.05],'HorizontalAlignment','left',...
      'Style','popup','Value',1,...
      'String',['Fattorizzazione LU            ';...
         'Fattorizzazione di Cholesky   ';...
         'Metodo del gradiente coniugato';...
         'Metodo del BiCGStab           ';...
         'Metodo del GMRES              '],...
      'BackgroundColor',AQUAMARINE,'Value',1,'Visible','off',...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue'); 
else
   uicontrol('Units','normalized',...
      'Position',[0.05 0.5 0.1 0.05],'HorizontalAlignment','left',...
      'Style','Text',...
      'String','Metodo:',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','red');
   METODO=uicontrol('Units','normalized',...
      'Position',[0.175 0.5 0.3 0.05],'HorizontalAlignment','left',...
      'Style','popup','Value',1,...
      'String',['Forward Euler          ';...
         'Backward Euler         ';...
         'Upwind                 ';...
         'Lax-Wendroff           ';],...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue',...
            'CallBack','time_step=delta_t_set;set(DELTAT,stringa,num2str(time_step));'); 
   uicontrol('Units','normalized',...
      'Position',[0.05 0.4 0.4 0.05],'HorizontalAlignment','left',...
      'Style','Text',...
      'String','Risolutore del sistema lineare: ',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','red');
   SOLVER(1)=uicontrol('Units','normalized',...
      'Position',[0.45 0.41 0.45 0.05],'HorizontalAlignment','left',...
      'Style','popup','Value',1,...
      'String',['LU Factorisation              ';...
         'Conjugate Gradient            ';...
         'BiCG                          ';...
         'BiCGStab                      ';...
         'CGS                           ';...
         'GMRES                         '],...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue'); 
   uicontrol('Units','normalized',...
      'Position',[0.05 0.3 0.3 0.05],'HorizontalAlignment','left',...
      'Style','Text',...
      'String','Preconditioner   : ',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','red');
   SOLVER(2)=uicontrol('Units','normalized',...
      'Position',[0.35 0.31 0.45 0.05],'HorizontalAlignment','left',...
      'Style','popup','Value',1,...
      'String',['No preconditioner  ';...
         'Diagonal  norm  2  ';...
         'ILU(0)             ';...
         'MILU               '],...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue');
end
uicontrol('Position',[100 30 100 40],'Style','PushButton',...
   'String','GO    ','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],'CallBack',...
   'if get(METODO,value)==4, info_supp; else, postprocdefhyp; end;')%
% scelta del Delta t: il Delta t è messo di default al massimo ammissibile secondo la CFL
%
uicontrol('Units','normalized',...
   'Position',[0.05 0.17 0.8 0.08],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','Delta t =       			    (default:max <= CFL)',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
   'FontWeight','demi','FontSize',[10]); 
DELTAT =uicontrol('Units','normalized',...
      'Position',[0.35 0.2 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0.1',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],...
      'ForegroundColor','blue','CallBack','dt=str2num(get(DELTAT,stringa));if dt<0, gest_errori(9);end;'); 
   
time_step=delta_t_set;   
set(DELTAT,'String',num2str(time_step));   



return;
