function info_supp
%
%   See also FEM1D.

%   Reference: A. Quarteroni, Modellistica Numerica 
%   per Problemi Differenziali, Springer-Italia, Milano
%   (2000).

%   Fausto Saleri, Alessandro Veneziani
%   $Revision: 1.1.1.1 $  $Date: 2001/03/09 08:22:48 $
global AQUAMARINE RELDATA METODO SOLVER
global MODUS FEMSYS GERBASE HMESH QUADRA
global FATHER FORMA CHOICE
global DELTAT OMEGA LUMPING SUPP
%
[figurePos]=pos_figure;
%
% Crea la figura
FATHER(6)=figure('NumberTitle','off','Color',AQUAMARINE,...
      'Units','points',...
      'MenuBar','none','Name',...
      'Fem 1D: Additional data for Lax-Wendroff.',...
      'Resize','off','Position',figurePos);
%
% Costruisce titolo, autori e release
cornici('no ');
uicontrol('Units','normalized',...
   'Position',[0.4 0.90 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','f_t = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12],'ForegroundColor','red'); 
%
SUPP(1) =uicontrol('Units','normalized',...
      'Position',[0.67 0.90 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[12],'ForegroundColor','blue');
%   
uicontrol('Units','normalized',...
   'Position',[0.4 0.80 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','f_x = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12],'ForegroundColor','red'); 
SUPP(2) =uicontrol('Units','normalized',...
      'Position',[0.67 0.80 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[12],'ForegroundColor','blue');
%   
uicontrol('Units','normalized',...
   'Position',[0.4 0.70 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','a_t = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12],'ForegroundColor','red'); 
SUPP(3) =uicontrol('Units','normalized',...
      'Position',[0.67 0.70 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[12],'ForegroundColor','blue');
%   
uicontrol('Units','normalized',...
   'Position',[0.4 0.60 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','a_x = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12],'ForegroundColor','red'); 
SUPP(4) =uicontrol('Units','normalized',...
      'Position',[0.67 0.60 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[12],'ForegroundColor','blue');
uicontrol('Units','normalized',...
   'Position',[0.4 0.50 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','a_xx = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12],'ForegroundColor','red'); 
SUPP(5) =uicontrol('Units','normalized',...
      'Position',[0.67 0.50 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[12],'ForegroundColor','blue');
uicontrol('Units','normalized',...
   'Position',[0.4 0.40 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','sigma_x = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12],'ForegroundColor','red'); 
SUPP(6) =uicontrol('Units','normalized',...
      'Position',[0.67 0.40 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[12],'ForegroundColor','blue');
   
%   
uicontrol('Position',[100 30 100 40],'Style','PushButton',...
   'String','GO','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],'CallBack',...
   'postprocdefhyp,');

return;
