function info_supp
%
%   See also FEM1D.

%   Reference: A. Quarteroni, Modellistica Numerica 
%   per Problemi Differenziali, Springer-Italia, Milano
%   (2000).

%   Fausto Saleri, Alessandro Veneziani
%   $Revision: 1.1.1.1 $  $Date: 2001/03/09 08:22:48 $
global AQUAMARINE RELDATA METODO SOLVER
global MODUS FEMSYS GERBASE HMESH QUADRA
global FATHER FORMA CHOICE
global DELTAT OMEGA LUMPING SUPP
%
[figurePos]=pos_figure;
%
% Crea la figura
FATHER(10)=figure('NumberTitle','off','Color',AQUAMARINE,...
      'Units','points',...
      'MenuBar','none','Name',...
      'Fem 1D: Additional information for Lax-Wendroff.',...
      'Resize','off','Position',figurePos);
%
% Costruisce titolo, autori e release
cornici('no ');
uicontrol('Units','normalized',...
   'Position',[0 0.95 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','f_t = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
%
SUPP(1) =uicontrol('Units','normalized',...
      'Position',[0.67 0.95 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue');
%   
uicontrol('Units','normalized',...
   'Position',[0 0.90 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','f_x = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
SUPP(2) =uicontrol('Units','normalized',...
      'Position',[0.67 0.90 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue');
%   
uicontrol('Units','normalized',...
   'Position',[0 0.85 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','a_t = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
SUPP(3) =uicontrol('Units','normalized',...
      'Position',[0.67 0.85 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue');
%   
uicontrol('Units','normalized',...
   'Position',[0 0.80 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','a_x = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
SUPP(4) =uicontrol('Units','normalized',...
      'Position',[0.67 0.6 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue');
uicontrol('Units','normalized',...
   'Position',[0 0.75 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','a_xx = ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
SUPP(5) =uicontrol('Units','normalized',...
      'Position',[0.67 0.75 0.1 0.05],'HorizontalAlignment','left',...
      'Style','edit','String','0',...
      'BackgroundColor',AQUAMARINE,...
      'FontWeight','demi','FontSize',[10],'ForegroundColor','blue');
uicontrol('Position',[100 30 100 40],'Style','PushButton',...
   'String','GO','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],'CallBack',...
   'postprocdefhyp');

return;
