function input2diffox
global AQUAMARINE RELDATA HMESH FEMSYS QUADRA USCITA AN_ERR INFO
%
% Posiziona la figura
[figurePos]=pos_figure;
%
% Dichiara il pannello iniziale
father=figure('NumberTitle','off','Color',AQUAMARINE,'Units','points',...
   'MenuBar','none','Name','Fem 1D. Model Problem   ','Resize','off',...
   'Position',figurePos);
%
% Costruisce titolo, autori e data
cornici('no ');
uicontrol('Units','normalized',...
   'Position',[0 0.95 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','Input the attributes of the numerical method:',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
%
% Tipo di elemento finito
uicontrol('Units','normalized',...
   'Position',[0.05 0.8 0.4 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','Finite element type    :',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
   'FontWeight','demi','FontSize',[10]); 
FEMSYS=uicontrol('Units','normalized',...
   'Position',[0.35 0.81 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Popup','String',['P1';'P2';'P3'],...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'ForegroundColor','blue'); 
%
% Tipo di griglia
uicontrol('Units','normalized',...
   'Position',[0.05 0.7 0.4 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','Grid Spacing     (uniform ) :',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
   'FontWeight','demi','FontSize',[10]); 
HMESH =uicontrol('Units','normalized',...
   'Position',[0.41 0.7 0.1 0.05],'HorizontalAlignment','left',...
   'Style','edit','String','0.1',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],...
   'ForegroundColor','blue'); 
QUADRA =uicontrol('String','0','Visible','off');
%
% Amenicoli vari
AN_ERR(1)=uicontrol('Value',0,'Visible','off');
%
% Crea il bottone di esecuzione
esegui=uicontrol('Units','normalized',...
   'Position',[0.05 0.1 0.2 0.08],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','GO    ','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],...
   'CallBack','set(INFO,visible,ON);exe_diffox; dis_diffox;');
%
% Info
INFO=uicontrol('Units','normalized',...
   'Position',[0.35 0.1 0.40 0.08],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','(move the legend with the mouse)',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','normal','FontSize',[8],'Visible','off',...
   'CallBack','exe_diffox; dis_diffox;');
%
% Crea il bottone di terminazione del caso test
esci=uicontrol('Units','normalized',...
   'Position',[0.7 0.1 0.25 0.08],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','Exit','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],...
   'CallBack','close all; fem1dmain;');

return