function iperbolico
%
%
%
global AQUAMARINE RELDATA CHOICE METODO
global CHOICE BC_DX BC_SX HMESH QUADRA SOLVER
global MODUS OMEGA FORMA BCVALUE FEMSYS GERBASE DER_CON
global USCITA AN_ERR
global FATHER
global MODELLI MODELS
global coord uh mat_fem infl
global INITC TIME SERVICE
close all;
%
% Posiziona la figura
[figurePos]=pos_figure;
%
% Crea la figura
FATHER(2)=figure('NumberTitle','off','Color',AQUAMARINE,...
   'Units','points',...
   'MenuBar','none','Name','Fem 1D: Hyperbolic Problem ',...
   'Resize','off','Position',figurePos);
%
% Costruisce titolo, autori e release
cornici('no ');
uicontrol('Units','normalized',...
   'Position',[0 0.95 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String',...
   'Choose formulation and input the coefficents (constant           )',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]); 
%
infl = 0; %inflow di default a sinistra
% Definizione delle due forme (conservativa e non) del problema.
space = blanks(18);
forma_1 = ['u_t + (',space,'u)_x +',space,'u =',...
      space];
forma_2 = ['u_t + ',space,'  u_x +',space,'u =',...
      space];
FORMA(1,5)=uicontrol('Units','normalized',...
   'Position',[0.1 0.68 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String',forma_1,'ForegroundColor','red',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off');
FORMA(2,5)=uicontrol('Units','normalized',...
   'Position',[0.1 0.68 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String',forma_2,'ForegroundColor','red',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off');
%
% Bottone di scelta nel caso a coefficienti costanti
CHOICE(3)=uicontrol('Units','normalized',...
   'Position',[0.91 0.96 0.02 0.03],'HorizontalAlignment','left',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[12],...
   'Style','radiobutton','String',' ','Value',1);
%

% Scelta della modalita' avanzata
MODUS=uicontrol('Units','normalized',...
   'Position',[0.3 0.08 0.425 0.05],'HorizontalAlignment','left',...
   'Style','radiobutton','String','advanced mode        ',...
   'FontAngle','oblique','ForegroundColor','red','Value',0,...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14]);
ESEGUI1=uicontrol('Units','normalized',...
   'Position',[0.1 0.055 0.2 0.1],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','Esegui','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],'CallBack',...
   'if str2num(get(OMEGA(2),stringa))<=str2num(get(OMEGA(1),stringa)), gest_errori(2); else  femdefhyp;  end;');
uicontrol('Units','normalized',...
   'Position',[0.75 0.055 0.2 0.1],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','Exit','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],'CallBack',...
   'close all; clear all; fem1dmain;');

% Coefficienti della forma conservativa.
FORMA(1,1)=uicontrol('Units','normalized',...
   'Position',[0.175 0.68 0.11 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off','callback','if get(FORMA(1,1),stringa)==zero, gest_errori(3), else smista_coef_bc(1,3); infl=quale_inflow; end;');  % viscosita'
FORMA(1,2)=uicontrol('Units','normalized',...
   'Position',[0.380 0.68 0.11 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off'); % termine reattivo
FORMA(1,3)=uicontrol('Units','normalized',...
   'Position',[0.550 0.68 0.11 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off');  % termine forzante
%
% Coefficienti della forma non conservativa.
FORMA(2,1)=uicontrol('Units','normalized',...
   'Position',[0.175 0.68 0.11 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10],'Visible','off','callback','if get(FORMA(2,1),stringa)==zero, gest_errori(3), else ,smista_coef_bc(0,3); infl=quale_inflow; end;');  % viscosita'
FORMA(2,2)=uicontrol('Units','normalized',...
   'Position',[0.380 0.68 0.11 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off'); %termine reattivo
FORMA(2,3)=uicontrol('Units','normalized',...
   'Position',[0.550 0.68 0.11 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off');  % termine forzante
%
%
% Bottoni di scelta tra le due forme
CHOICE(1)=uicontrol('Units','normalized',...
   'Position',[0.02 0.86 0.6 0.06],'HorizontalAlignment','left',...
   'BackgroundColor',AQUAMARINE,'Value',0,...
   'FontWeight','demi','FontSize',[12],...
   'Style','radiobutton','String','Conservative Form ','CallBack',...
   'set(CHOICE(1),value,1);set(CHOICE(2),value,0);call_xor(FORMA(1,:),visible,ON,ON);call_xor(FORMA(2,:),visible,OFF,OFF);[dc_sx,dc_dx]=der_co_nom(1);'); 
CHOICE(2)=uicontrol('Units','normalized',...
   'Position',[0.02 0.76 0.6 0.06],'HorizontalAlignment','left',...
   'BackgroundColor',AQUAMARINE,'Value',0,...
   'FontWeight','demi','FontSize',[12],...
   'Style','radiobutton','String','Non Conservative Form ','CallBack',...
   'set(CHOICE(1),value,0);set(CHOICE(2),value,1);call_xor(FORMA(1,:),visible,OFF,OFF);call_xor(FORMA(2,:),visible,ON,ON);[dc_sx,dc_dx]=der_co_nom(0);');
%
% Definizione degli estremi dell'intervallo computazionale.
uicontrol('Units','normalized',...
   'Position',[0 0.58 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'in (          ,          ) x (          ,          ), with boundary conditions   ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[12]);
OMEGA(1)=uicontrol('Units','normalized',...
   'Position',[0.06 0.58 0.07 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10],'CallBack',...
   'if str2num(get(OMEGA(2),stringa))<=str2num(get(OMEGA(1),stringa)), gest_errori(2); else smista_coef_bc(get(CHOICE(1),value),3), end;');

OMEGA(2)=uicontrol('Units','normalized',...
   'Position',[0.16 0.58 0.07 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'CallBack',...
   'if str2num(get(TIME(2),stringa))<str2num(get(TIME(1),stringa)), gest_errori(8); else smista_coef_bc(get(CHOICE(1),value),3), end;');

TIME(1)=uicontrol('Units','normalized',...
   'Position',[0.30 0.58 0.07 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10],'CallBack',...
   'if str2num(get(TIME(2),stringa))<str2num(get(TIME(1),stringa)), gest_errori(8); else ,smista_coef_bc(get(CHOICE(1),value),3), end;');

TIME(2)=uicontrol('Units','normalized',...
   'Position',[0.40 0.58 0.07 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'CallBack',...
   'if str2num(get(OMEGA(2),stringa))<=str2num(get(OMEGA(1),stringa)), gest_errori(2); else smista_coef_bc(get(CHOICE(1),value),3), end;');
%
%
% Definizione delle condizioni al contorno
SERVICE(1)=uicontrol('Units','normalized',...
   'Position',[0.06 0.52 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','magenta','String',...
   'Estremo sinistro',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[12],'Visible','on');
%
SERVICE(2)=uicontrol('Units','normalized',...
   'Position',[0.66 0.52 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','magenta','String',...
   'Estremo destro',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[12],'Visible','off');

%[dc_sx,dc_dx]=der_co_nom(0);
% Dirichlet a sinistra (default)
BC_SX(1)=uicontrol('Units','normalized',...
   'Position',[0.02 0.46 0.02 0.03],'HorizontalAlignment','left',...
   'BackgroundColor',AQUAMARINE,'Value',1,...
   'FontWeight','demi','FontSize',[12],...
   'Style','radiobutton','String',' ','CallBack',...
   'set(BC_SX(2),value,0);set(BC_SX(3),value,0);set(BC_SX(1),value,1);'); 
SERVICE(3)=uicontrol('Units','normalized',...
   'Position',[0.07 0.45 0.05 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','u  = ','ForegroundColor','red',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
BCVALUE(1,1) =uicontrol('Units','normalized',...
   'Position',[0.15 0.45 0.3 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','on');
%
% Neumann estremo di sinistra
%BC_SX(2)=uicontrol('Units','normalized',...
%   'Position',[0.02 0.35 0.02 0.03],'HorizontalAlignment','left',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[12],...
%   'Style','radiobutton','String',' ','Visible','on','CallBack',...
%   'set(BC_SX(1),value,0);set(BC_SX(2),value,1);set(BC_SX(3),value,0);'); 
%DER_CON(1,1)=uicontrol('Units','normalized',...
%   'Position',[0.05 0.34 0.1 0.05],'HorizontalAlignment','left',...
%   'Style','Text',...
%   'String',cat(2,dc_sx,' = '),'ForegroundColor','red',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','on');
%BCVALUE(2,1) =uicontrol('Units','normalized',...
%   'Position',[0.15 0.34 0.3  0.05],'HorizontalAlignment','left',...
%   'Style','Edit',...
%   'String','0','ForegroundColor','blue',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','on');
%
% Robin a sinistra
%BC_SX(3)=uicontrol('Units','normalized',...
%   'Position',[0.02 0.24 0.02 0.03],'HorizontalAlignment','left',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[12],...
%   'Style','radiobutton','String',' ','Visible','on','CallBack',...
%   'set(BC_SX(2),value,0);set(BC_SX(1),value,0);set(BC_SX(3),value,1);'); 
%DER_CON(1,2)=uicontrol('Units','normalized',...
%   'Position',[0.05 0.23 0.1 0.05],'HorizontalAlignment','left',...
%   'Style','Text',...
%   'String',cat(2,dc_sx,' + '),'ForegroundColor','red',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','on');
%BCVALUE(3,1)=uicontrol('Units','normalized',...
%   'Position',[0.15 0.23 0.1 0.05],'HorizontalAlignment','left',...
%   'Style','Edit',...
%   'String','1','ForegroundColor','blue',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','on');
%SERVICE(4)=uicontrol('Units','normalized',...
%   'Position',[0.25 0.23 0.05 0.05],'HorizontalAlignment','left',...
%   'Style','Text',...
%   'String',' u = ','ForegroundColor','red',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','on');
%BCVALUE(4,1) =uicontrol('Units','normalized',...
%   'Position',[0.3 0.23 0.15 0.05],'HorizontalAlignment','left',...
%   'Style','Edit',...
%   'String','0','ForegroundColor','blue',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','on');

%
% Dirichlet a destra (default)
BC_DX(1)=uicontrol('Units','normalized',...
   'Position',[0.52 0.46 0.02 0.03],'HorizontalAlignment','left',...
   'BackgroundColor',AQUAMARINE,'Value',0,...
   'FontWeight','demi','FontSize',[12],...
   'Style','radiobutton','String',' ','CallBack',...
   'set(BC_DX(2),value,0);set(BC_DX(3),value,0);set(BC_DX(1),value,1);',...
   'Visible','off'); 
SERVICE(5)=uicontrol('Units','normalized',...
   'Position',[0.57 0.45 0.05 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','u  =      ','ForegroundColor','red',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off');
BCVALUE(1,2) =uicontrol('Units','normalized',...
   'Position',[0.65 0.45 0.3 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'Visible','off');
%
% Neumann a destra
%BC_DX(2)=uicontrol('Units','normalized',...
%   'Position',[0.52 0.35 0.02 0.03],'HorizontalAlignment','left',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[12],...
%   'Style','radiobutton','String',' ','CallBack',...
%   'set(BC_DX(1),value,0);set(BC_DX(2),value,1);set(BC_DX(3),value,0);',...
%   'Visible','off'); 
%DER_CON(2,1)=uicontrol('Units','normalized',...
%   'Position',[0.55 0.34 0.1 0.05],'HorizontalAlignment','left',...
%   'Style','Text',...
%   'String',cat(2,dc_dx,' = '),'ForegroundColor','red',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','off');
%BCVALUE(2,2) =uicontrol('Units','normalized',...
%   'Position',[0.65 0.34 0.3 0.05],'HorizontalAlignment','left',...
%   'Style','Edit',...
%   'String','1','ForegroundColor','blue',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','off');
%%
%% Robin a destra
%BC_DX(3)=uicontrol('Units','normalized',...
%   'Position',[0.52 0.24 0.02 0.03],'HorizontalAlignment','left',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[12],...
%   'Style','radiobutton','String',' ','CallBack',...
%   'set(BC_DX(2),value,0);set(BC_DX(1),value,0);set(BC_DX(3),value,1);',...
%   'Visible','off'); 
%DER_CON(2,2)=uicontrol('Units','normalized',...
%   'Position',[0.55 0.23 0.1 0.05],'HorizontalAlignment','left',...
%   'Style','Text',...
%   'String',cat(2,dc_dx,' + '),'ForegroundColor','red',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','off');
%BCVALUE(3,2)=uicontrol('Units','normalized',...
%   'Position',[0.65 0.23 0.1 0.05],'HorizontalAlignment','left',...
%   'Style','Edit',...
%   'String','1','ForegroundColor','blue',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','off');
%SERVICE(6)=uicontrol('Units','normalized',...
%   'Position',[0.75 0.23 0.05 0.05],'HorizontalAlignment','left',...
%   'Style','Text',...
%   'String',' u = ','ForegroundColor','red',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','off');
%BCVALUE(4,2) =uicontrol('Units','normalized',...
%   'Position',[0.8 0.23 0.15 0.05],'HorizontalAlignment','left',...
%   'Style','Edit',...
%   'String','1','ForegroundColor','blue',...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'Visible','off');
%%
% condizioni iniziali
%
uicontrol('Units','normalized',...
   'Position',[0.01 0.16 0.55 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','e condizioni iniziali','ForegroundColor','black',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[12],'FontAngle','oblique');
uicontrol('Units','normalized',...
    'Position',[0.32 0.16 0.55 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','u_0 =','ForegroundColor','red',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
INITC =uicontrol('Units','normalized',...
   'Position',[0.4 0.16 0.25 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
%
return
