 function model
%
%MODELLO 1-d finite element model problems.
%   MODELLO is the graphical interface for the finite
%   element one-dimensional model problems.
%
%   See also FEM1D.

%   Fausto Saleri, Alessandro Veneziani
%   $Revision: 1.1.1.1 $  $Date: 2001/03/09 08:22:48 $
global AQUAMARINE RELDATA MODELLI MODELS
close all;
%
% Posiziona la figura
[figurePos]=pos_figure;
%
% Crea la figura
father=figure('NumberTitle','off','Color',AQUAMARINE,...
   'Units','points',...
   'MenuBar','none','Name','Fem 1D: problemi modello',...
   'Resize','off','Position',figurePos);
%
% Costruisce titolo, autori e release
cornici('no ');
uicontrol('Units','normalized',...
   'Position',[0 0.95 1 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String',...
   'Choose the model problem you wish to study:',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]);
v = 'Value';
%
% Cerca i problemi modello disponibili nella directory
% corrente e li carica in una lista
MODELS = dir('pb1d_*.m');
[n,m]=size(MODELS);
L=[]; for i=1:n, L = [L, length(MODELS(i).name)]; end
Lmax = max(L); models_list = [];
for i=1:n
   temp = MODELS(i).name;
   models_list = [models_list; [temp(1:end-2),blanks(Lmax-L(i))]];
end
models_list=models_list(:,6:end);
for i = 1:n
   models_list(i,:)=strrep(models_list(i,:),'_',' ');
end
MODELLI=uicontrol('Units','normalized',...
   'Position',[0.15 0.52 0.7 0.4],'HorizontalAlignment','left',...
   'Style','List','Value',1,...
   'String',models_list,'ForegroundColor','red',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],...
   'CallBack','about_model');
uicontrol('Units','normalized',...
   'Position',[0.15 0.1 0.25 0.08],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','GO','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],'CallBack',...
   'com=MODELS(get(MODELLI,value)).name; eval(com(1:end-2))');
return
