function pb1d_cuscinetto_a_sfera
%
% Lubricated slider
% We determine the pressure on the surface of a lubricated slider
% which moves in th efhorizontal direction with conmnstant velocity U
% The slider is separated from the support by a thin film of
% lubricant (viscous liquid)
%
% Type of problem: elliptic with non-constant coefficents.
%
%%
global AQUAMARINE RELDATA FORMA OMEGA CHOICE
%
% Posiziona la figura
close all;
[figurePos]=pos_figure;
%
% Dichiara il pannello iniziale
father=figure('NumberTitle','off','Color',AQUAMARINE,'Units','points',...
   'MenuBar','none','Name','Fem 1D. Model Problem','Resize','off',...
   'Position',figurePos);
%
% Costruisce titolo, autori e release
cornici('no ');
%
% Breve descrizione dei parametri del problema differenziale.
topic={...
   'Let us consier a lubricated  slider of length  L which     '
   'may slide in the direction x over a support. A thin layer  '
   'of lubricant (a viscous fluid) separates the slider from  '
   'the support. Let assume that the slider moves at velocity U'
   'with respect to the support (who is of infinite length)   '
   'The surface of the slider is defined by a function s=s(x) '
   'The pressure between the slider and the support obeys the '
   'following homogeneous   Dirichlet problem :               '
   '                                                          '
   '  -[(s(x))^3/(6 mu)] p''(x)]'' = -( U s(x) )'' 0<x<L '
   '  p(0) = 0                                                '
   '  p(L) = 0                                                '
   '                                                          '
   'where  mu > 0 is  the viscosity (constant) of the lubricant'};
uicontrol('Units','normalized',...
   'Position',[0.01 0.65 0.65 0.3],'HorizontalAlignment','left',...
   'Style','list','String',topic,...
   'ForegroundColor','black',... 
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','normal','FontSize',[10]);
%
% Definizione dei parametri del problema modello
uicontrol('Units','normalized',...
   'Position',[0.01 0.575 0.65 0.05],'HorizontalAlignment','left',...
   'Style','Text','ForegroundColor','magenta',...
   'String',...
   'Input the parameters of the problem: ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]);
%
% Forma dell'equazione
CHOICE(1)=uicontrol('Visible','off','Value',1);
%
% Lunghezza del cuscinetto
uicontrol('Units','normalized',...
   'Position',[0.03 0.475 0.4 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Slider Length                L = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
OMEGA(1)=uicontrol('Visible','off','String','0');
OMEGA(2)=uicontrol('Units','normalized',...
   'Position',[0.45 0.475 0.15 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
% Non capisco perche' a me non funziona!
%,'CallBack',...
%   'if str2num(get(OMEGA(2),stringa))<= 0, gest_errori(2); else smista_coef_bc(get(CHOICE(1),value)), end;');
%
% Forma del cuscinetto
uicontrol('Units','normalized',...
   'Position',[0.03 0.375 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Slider Surface              s(x) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,1)=uicontrol('Units','normalized',...
   'Position',[0.45 0.375 0.3 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1 - 3/2*x + 9/8*x^2',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
%
% Viscosita' del lubrificante
uicontrol('Units','normalized',...
   'Position',[0.03 0.275 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Lubricant viscosity            mu = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,2)=uicontrol('Units','normalized',...
   'Position',[0.45 0.275 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
%
% Velocita' del cuscinetto
uicontrol('Units','normalized',...
   'Position',[0.03 0.175 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Slider Velocity,  U = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,4)=uicontrol('Units','normalized',...
   'Position',[0.45 0.175 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,3)=uicontrol('String','0','Visible','off');
FORMA(1,5)=uicontrol('String','0','Visible','off');
%
% Descrizione grafica del caso test
subplot(3,3,3); x=[0:0.01:1];
f=1 - 3/2*x + 9/8*x.^2;
f=[f 1]; x=[x 1];
patch(x,f,'red'); patch([0 1 1 0],[-0.3 -0.3 -0.1 -0.1],'red');
testo=text(0,0.6,'s(x)');
set(testo,'FontSize',12)
testo=text(0.75,0.2,'U');
set(testo,'FontSize',12);
hold on; H=feather(-0.5,0); 
set(H(1),'Color','black');set(H(2),'Color','black');
set(H(1),'LineWidth',1.5); set(H(2),'LineWidth',2);
axis off; hold off;
%
% Crea il bottone di esecuzione
esegui=uicontrol('Units','normalized',...
   'Position',[0.035 0.085 0.25 0.07],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','GO    ','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],...
   'CallBack','input2cusci');