function pb1d_blood_flow_1d
%
% 1D Models for compliant vessels: 
% 
% Nonlinear Hyperbolic System 
% solved by the Lax-Wendroff Method
% 
% by F. Nobile
% 
%
%%
global AQUAMARINE RELDATA FORMA OMEGA CHOICE
%
% Posiziona la figura
close all;
[figurePos]=pos_figure;
%
% Dichiara il pannello iniziale
father=figure('NumberTitle','off','Color',AQUAMARINE,'Units','points',...
   'MenuBar','none','Name','Fem 1D. Model Problem','Resize','off',...
   'Position',figurePos);
%
% Costruisce titolo, autori e release
cornici('no ');
%
% Breve descrizione dei parametri del problema differenziale.
topic={...
   'Let us consider the description of blood flow in a   ' 
   'cylindrical compliant vessel. We are supposing that '
   'the constitutive law relating the blood pressure to ' 
   'the section area is an algebraic one.                ' 
   'The model obtained is a system of Hyperbolic        '
   'equations, involving the Area (related to the       '
   'pressure) and the flow rate.                         '};
uicontrol('Units','normalized',...
   'Position',[0.01 0.85 0.65 0.15],'HorizontalAlignment','left',...
   'Style','list','String',topic,...
   'ForegroundColor','black',... 
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','normal','FontSize',[10]);
%
% Definizione dei parametri del problema modello
uicontrol('Units','normalized',...
   'Position',[0.01 0.8 0.65 0.05],'HorizontalAlignment','left',...
   'Style','Text','ForegroundColor','magenta',...
   'String',...
   'Input the parameters of the problem: ',...
   'BackgroundColor',AQUAMARINE,'FontAngle','oblique',...
   'FontWeight','demi','FontSize',[12]);
%
% Forma dell'equazione
CHOICE(1)=uicontrol('Visible','off','Value',1);
%
% Lunghezza del vaso 
uicontrol('Units','normalized',...
   'Position',[0.03 0.75 0.4 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Vessel Length (cm)  = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
OMEGA(1)=uicontrol('Visible','off','String','0');
OMEGA(2)=uicontrol('Units','normalized',...
   'Position',[0.30 0.75 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','30','ForegroundColor','blue',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],...
   'CallBack',...
   'if str2num(get(OMEGA(2),stringa))<= 0, gest_errori(2); else smista_coef_bc(get(CHOICE(1),value)), end;');
%
% Altri parametri 
uicontrol('Units','normalized',...
   'Position',[0.03 0.7 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Reference Radius (cm) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,1)=uicontrol('Units','normalized',...
   'Position',[0.30 0.7 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0.5',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
%
uicontrol('Units','normalized',...
   'Position',[0.03 0.65 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Density (g/cm^3) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,2)=uicontrol('Units','normalized',...
   'Position',[0.3 0.65 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1.1',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
%
uicontrol('Units','normalized',...
   'Position',[0.03 0.60 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Young m. (g/(cm*s^2)) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,4)=uicontrol('Units','normalized',...
   'Position',[0.3 0.60 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','3*10^6',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
uicontrol('Units','normalized',...
   'Position',[0.03 0.55 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Thickness (cm) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,5)=uicontrol('Units','normalized',...
   'Position',[0.3 0.55 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0.1',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
uicontrol('Units','normalized',...
   'Position',[0.03 0.5 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Coriolis coef(adim) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,6)=uicontrol('Units','normalized',...
   'Position',[0.3 0.5 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);%
uicontrol('Units','normalized',...
   'Position',[0.03 0.45 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Viscosity (poise) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,7)=uicontrol('Units','normalized',...
   'Position',[0.3 0.45 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0.035',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
uicontrol('Units','normalized',...
   'Position',[0.03 0.4 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Initial Time (sec) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,8)=uicontrol('Units','normalized',...
   'Position',[0.3 0.4 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
uicontrol('Units','normalized',...
   'Position',[0.03 0.35 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Time Step (sec) = ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,9)=uicontrol('Units','normalized',...
   'Position',[0.3 0.35 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0.00005',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
uicontrol('Units','normalized',...
   'Position',[0.03 0.3 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Num Time Steps =  ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,10)=uicontrol('Units','normalized',...
   'Position',[0.3 0.3 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1000',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
uicontrol('Units','normalized',...
   'Position',[0.03 0.25 0.45 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Mesh size (cm) =  ',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,11)=uicontrol('Units','normalized',...
   'Position',[0.3 0.25 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','0.1',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);

uicontrol('Units','normalized',...
   'Position',[0.5 0.65 0.4 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'String','Forcing term:',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
   'FontWeight','demi','FontSize',[10]); 
s='String';
FORMA(1,12)=uicontrol('Units','normalized',...
   'Position',[0.75 0.66 0.2 0.05],'HorizontalAlignment','left',...
   'Style','Popup','String',['const.';'linear';'sinus.'],...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10],'ForegroundColor','blue'); 
%uicontrol('Units','normalized',...
%   'Position',[0.5 0.5 0.4 0.05],'HorizontalAlignment','left',...
%   'Style','Text',...
%   'String','BC Treatment:',...
%   'BackgroundColor',AQUAMARINE,'ForegroundColor','red',...
%   'FontWeight','demi','FontSize',[10]); 
%s='String';
%FORMA(1,13)=uicontrol('Units','normalized',...
%   'Position',[0.75 0.51 0.2 0.05],'HorizontalAlignment','left',...
%   'Style','Popup','String',['Charact. ';'Dirichlet'],...
%   'BackgroundColor',AQUAMARINE,...
%   'FontWeight','demi','FontSize',[10],'ForegroundColor','blue'); 

uicontrol('Units','normalized',...
   'Position',[0.03 0.2 0.95 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Area boundary term =                  *(p0/2*beta)^2 (possible function of time)',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,3)=uicontrol('Units','normalized',...
   'Position',[0.3 0.2 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1.2',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
%%
uicontrol('Units','normalized',...
   'Position',[0.03 0.15 0.95 0.05],'HorizontalAlignment','left',...
   'Style','Text',...
   'ForegroundColor','black','String',...
   'Area initial =                              *(p0/2*beta)^2 (possible function of x)',...
   'FontAngle','oblique','BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[10]);
FORMA(1,13)=uicontrol('Units','normalized',...
   'Position',[0.3 0.15 0.1 0.05],'HorizontalAlignment','left',...
   'Style','Edit',...
   'String','1.0',...
   'BackgroundColor',AQUAMARINE,'ForegroundColor','blue',...
   'FontWeight','demi','FontSize',[10]);
%
% Crea il bottone di esecuzione
esegui=uicontrol('Units','normalized',...
   'Position',[0.035 0.085 0.25 0.07],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','GO    ','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],...
   'CallBack','addpath ../../1DHYP; main_template; ');
esci=uicontrol('Units','normalized',...
   'Position',[0.7 0.085 0.25 0.07],'HorizontalAlignment','left',...
   'Style','PushButton',...
   'String','Exit','FontAngle','oblique',...
   'BackgroundColor',AQUAMARINE,...
   'FontWeight','demi','FontSize',[14],'CallBack',...
   'close all; clear all;fem1d');
